### PR TITLE
[FIX] Bug in setAvatar while updating user avatar

### LINKED ISSUE #76: [BUG] Set Avatar not working
The `setAvatar(filename, mimeType)` function is not working. This is possibly happening because of incorrect form field provided in the code. See below:

https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/d7046444b10fbd68df1edd2138ee38bcb981aad4/core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt#L100

It should be `image` instead of `image=`

### PR DESCRIPTION
**Pull request by aniketsingh03**
Fixes #76 .

The `setAvatar` was not working due to the problem mentioned in the issue. I have fixed it in this pr.

### CODE REVIEW

**Comment by aniketsingh03** [comment]
@rafaelks can you have a look at this one?

**Comment by rafaelks** [comment]
@filipedelimabrito Please, review this one.

**Comment by aniketsingh03** [comment]
Can you review this @filipedelimabrito ?

**Comment by filipedelimabrito** [comment]
Thank you for this PR @aniketsingh03!

**Pull request merged**
