### PR TITLE
[NEW] Support for querying users based on regex.

### PR DESCRIPTION
**Pull request by aniketsingh03**
Fixes https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/issues/99

### CODE REVIEW

**Comment by aniketsingh03** [comment]
@luciofm @rafaelks can you have a look at it?

**Comment by rafaelks** [comment]
@aniketsingh03 Where is this API going to be used? 🤔

**Comment by rafaelks** [comment]
@aniketsingh03 Thank you for the PR! 👍

**Comment by aniketsingh03** [comment]
@rafaelks This api is going to be used in https://github.com/RocketChat/Rocket.Chat.Android/pull/891

**Comment by rafaelks** [comment]
@aniketsingh03 Gotcha! Looks good to me! :-)

**Comment by aniketsingh03** [comment]
@rafaelks @luciofm can this be merged?

**Comment by rafaelks** [comment]
@leonardoaramaki Can you please review this one?

**Comment by rafaelks** [comment]
@aniketsingh03 I'm sorry for the delay, we'll be merging this one after `1.0.0` is released (very soon). 👍

**Comment by rafaelks** [comment]
@aniketsingh03 Thanks for the PR! 👍

**Pull request merged**
