### PR TITLE
[EXPERIMENT] Use kotlin-dsl to manage depencies...

### PR DESCRIPTION
**Pull request by luciofm**

### CODE REVIEW

**Comment by leonardoaramaki** [comment]
How fast is this compared to Gradle?

**Comment by luciofm** [comment]
@leonardoaramaki don't think it have any noticeable difference...

Was just experimenting with kotlin-dsl

**Comment by rafaelks** [comment]
@luciofm Do we want to keep this one opened?

**Comment by rafaelks** [comment]
Closing this one, looks inactive.

**Pull request closed without merging**
